### ISSUE TITLE
New Feature: Swerve tweaks

### ISSUE THREAD

**Issue by salut-hi** [Auth-Xero/9430-offseasonSwerve#4]
**Current problem**
Need to look over the drive subsystem and make any necessary tweaks for the test bot.

**Solution should be like**
Change of necessary constants so that the swerve runs smoothly and change gyro to pigeon

**Considered alternatives**
Do whatever will improve the functioning of the subsystem, if need be do more than what is stated in the solution.

**Acceptance Criteria**
- identify necessary swerve tweaks
- Change all affected consts.
- Pigeon implemented with no errors
- Driver controller must be responsive but not sensitive (drive team must confirm)

**List of identified things**
- Wheel Base (done)
- Wheel Diameter (done)
- Controller deadband

**Comment by bbontrager89** [comment]
All work for implementing field relative drive should be done on #6 . Changing gyro to pidgeon is required for completion of this issue, but field relative implementation is not required for completion of this issue.

**Comment by bbontrager89** [comment]
## 2024/11/21 18:00 -- Testing Results: 
### Expectations: 
	A. During this test, the robot should drive relative to itself as a measure of simplicity to test the swerve modules and drive subsystem. 
		- When moving forward, the robot should move towards its front (opposite the battery). 
		- When moving left, the robot should move to the left relative to its front
		- When moving right, robot should move right 
		- When moving backwards, the robot should move opposite to its front. 
		- When turning the robot, these reference points should remain the same. 
	B. Driver controller should be responsive yet not overly sensitive 
	C. Speed of robot should be relative to joystick position; ie. moving slightly forward should not max out speed

### Observations: 
	- Test A passed successfully; robot was able to drive relative to its own position and maintain relativity as expected. 
	- Test B failed; both thumbsticks are too sensitive. 
	- Test C passed successfully; robot speed is relative to joystick input. 
	- During an unrelated test, we attempted to test field oriented drive. Forward was defaulting to its front-left corner, 
	  and rotating the bot seemed to change its relative heading as well. 
		(note: Field Relative testing should occur on issue #6, and should have separate test cases)
	  
### Testing Summary
Robot centric drive functions flawlessly indicating the swerve modules are configured properly. Need to update controller deadband to reduce sensitivity. 

*As a sidenote, all testing should relate to one single issue, and all testing results should be documented. Testing expectations can be formulated from the acceptance criteria of the issue being tested. Tests pass when the observations match expectations set by cross-team collaboration*

If you have any questions about documenting test results or coming up with test cases, please reach out to me.

**Comment by bbontrager89** [comment]
Have the controller sensitivities been adjusted according to our testing results? We may close this issue after this has been resolved. If issues come up from something broken later, we can create bug reports.

**Comment by bbontrager89** [comment]
**__Branch should be assigned to #8 but we have some things we should do first__**:
1. `gyro` should currently have all working code committed to it. However, it's outdated because the fix for #6 was committed to `swerve-tweaks`. 
   1. Revert 9940c27dbeeac175985eadf16eb7e945e15bde59 from `swerve-tweaks`
   2. Apply those reverted changes manually to `gyro`. 
   3. This will clean up `swerve-tweaks` and properly update `gyro` with fixes for #6 . 
2. Let's also create a new branch called `swerve` to represent our working swerve subsystem code. `swerve-tweaks` was a branch we used to fix #4 , and when #4 is tested and approved, we can merge `swerve-tweaks` to `swerve`. 
3. Now, `gyro` and `swerve` can be considered "working branches" where we ensure these subsystems contain only working code. I will look into protecting these branches from developmental commits. 
4. Create a new branch for this issue 
   1. Name example: `8-swerve-drift-fix`
   2. Target repository should be set to `Auth-Xero/9430-offseasonSwerve`
   3. Click "Change Branch Source" and select `swerve` as the branch source. 
      1. *This is because we want to create a new branch based on only working changes. Other branches working on fixes for other issues related to our drivetrain may be in progress, so branching our fixes from working code will allow others to merge their fixes into `swerve` without affecting our work.*
   4. Click "Create Branch" and checkout the branch locally to VScode. This can be done by running `git checkout origin/8-swerve-drift-fix`.
      1. This will automatically create a new local branch called `8-swerve-drift-fix` and set its upstream to the origin branch of the same name. (`git push` will push changes to `origin/8-swerve-drift-fix`)
5. Do code and practice properly committing changes. 

Since we are fixing a bug related to the swerve drivetrain, we will want to eventually merge #8 into `swerve` (our "working swerve" branch) using a pull request to coordinate this effort.
